language: java

dist: xenial

jdk:
- openjdk8
 
services:
  # -----------------------------------------------------
  # Start up xvfb service for SWT bot GUI tests
  # -----------------------------------------------------
  - xvfb 
 
cache:
  directories:
  - $HOME/.m2

addons:
  # -----------------------------------------------------------
  # Make the sourceforge hosts known, thus ssh connections will
  # not ask to accept the finger print of the server
  # -----------------------------------------------------------
  ssh_known_hosts: frs.sourceforge.net
  # ---------------------------------------------------------------
  # Now use APT to install metacity, which is a window manager also 
  # needed for the SWTBOT UI tests
  # ---------------------------------------------------------------
  apt:
    packages:
    - libvtk6.2 # libvtk7.1 # for bionic. At the moment we are still with jdk8 which is on xenial only
    - libvtk6-java # libvtk7-java # for bionic
    # - libvtk7-jni # for bionic
    - libzmq5
    - libzmq-java
    - libzmq-jni
    - metacity
    - ant

install:
- true

stages:
# ------------------------------------
# Just one stage, multiple stages 
# with maven overcomplicate the things
# ------------------------------------
#- name: verify
- name: build-test
#- name: build-assemble-deploy

env:
  global:
  # ---------------------------------------------
  # API Token for access to github
  # ---------------------------------------------
  - secure: "POYGzbPXLBDe2BsehzJ7QUZ4toQ1Pbi2VdH8ZTSN9zqipLbBVnsMghs7Zf80C+AK1nKbY2DPWHwaWR6LE3MRhA9X3xeyYgJ/53J4JeMw1ORYpavVXJC9t8d+fMVCJhALzjQYz7PmE4ba/MHgr/UnoeNL2v1M/9mUpMbfD490jPUdOQjqpy0/FvM5HhXcQEwexUPsNsR+DffVSSmJ62aXHPM2pgKYaH0pnY5OYwm4t7v7lp8GgQf+b163+rD2LyLIEeLiQ1msXAqaRSBznuu2wqi7N3ZC176i864fRHf8M4RYbWqA0BneCd0keAQJLvpcPBoyE1T0XKYvjz5JdjbuNDX1p4waLo7CnU+UJzuCQ5hnkrDm7YJhwQY007T2kudUTPl0dP0TeoJsDtz30vvBC82equJA5+0xPb1BvvDmdKFkfF7gOGh05qjhAo3TJ8D5CXXFmdPr9VApYv0zqzh0hR5p+5FHkDmKhzJ7xg4jpo04IXa8ztBCjoB4dyLnUDhyTABtA5/uoRuMA4I7nc25mKL6Z9fz8O8HadAInlJFXyodQOrvD68k2Bf9WJWreZMKcLJiOWQC0bbPNa6ABrRpiuzdUdWEpzNjJJYktmPl+JwHAJ4Fa3CHaNFILaLLC9Z3gtrdNT2+PkME8u0sfVWZ1nU4nNO9EGUItcBEFhkCnZE="

  
after_failure:
  # ----------------------------------------
  # Decrypt the key for accessign the 
  # deployment store and add it to ssh-agent
  # then try to deploy the screenshots from 
  # SWTBot to see what happened 
  # ----------------------------------------
  - bash/deploy_sourceforge.sh -k $encrypted_9c25c12f834a_key -i $encrypted_9c25c12f834a_iv -u swtbot
  
jobs:
  include:

    
    # -----------------------------------------------------
    # Build and Test - Surefire Jobs
    # -----------------------------------------------------
    # --- Development and Feature Branches
    - stage: build-test
      name: Build and Test - Surefire - Test Sourceforge Upload
      script:
      - echo "test" > ${TRAVIS_HOME}/swtbot/test.txt
      - echo "test" > ${TRAVIS_HOME}/swtbot/test2.txt
      - echo "test" > ${TRAVIS_HOME}/swtbot/test3.txt
      - echo "test" > ${TRAVIS_HOME}/swtbot/test4.png
      - echo "test" > ${TRAVIS_HOME}/swtbot/test5.png
      - exit 1

 