name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: ./bash/setup.sh
 
      # Checks out a copy of your repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # --------------------------------------------
      # Run a quicksanity check if all commits are
      # handed in by known users
      #---------------------------------------------
      - name: Verify - Authors Sanity Check
        run: ./bash/verify_commit_authors.sh known_authors.txt
      
      - name: Build and Test - SpotBugs - Development and Features
        run: ./bash/maven_build.sh -j spotbugs -p development
