# --------------------------------------------
# This is a basic workflow to help you get started with Actions
# --------------------------------------------
name: Build

on:
  # --------------------------------------------
  # Controls when the automatic build job will be run.
  # By default uses the default branch. Runs at 03:00 UTC.
  # --------------------------------------------
  schedule:
    - cron: '0 3 * * *'
      
  # --------------------------------------------
  # Run this workflow every time a new commit pushed to the repository
  # --------------------------------------------
  push:
  
  # --------------------------------------------
  # Run this workflow every time a pull request is created or commited to it
  # --------------------------------------------
  pull_request:
    branches:
      - '**'

env:
  # -------------------------------------------------------------
  # Setting up locale to have correct keyboard mapping for swtbot
  # -------------------------------------------------------------
  LANG: "en_US.UTF-8"
# --------------------------------------------
# Defines the list of jobs
# --------------------------------------------
jobs:


  # -----------------------------------------------------
  # Build and Test - Checkstyle Job
  # -----------------------------------------------------
  checkstyle:
    name: Build and Test - Checkstyle
    runs-on: ubuntu-18.04
   
    steps:
    
      # --------------------------------------------
      # Development and Feature branches
      # --------------------------------------------
      - name: Build - Build and Deploy Decision
        id: build_decision
        uses: virtualsatellite/ci-actions/ci-build-decision-action@master
        
      - name: Build - Report build Decision
        run: |
          echo Build-Type: ${{ steps.build_decision.outputs.build_type }}
          echo Deploy-Type: ${{ steps.build_decision.outputs.deploy_type }}
         

    

 